namespace Bartrix.Modules.Listings.Contracts;

public sealed record ListingResponse(
    Guid Id,
    Guid OwnerUserId,
    string Title,
    string Description,
    string Category,
    string Condition,
    string Location,
    decimal? AskingPrice,
    bool IsAvailableForSwap,
    bool IsAvailableForSale,
    bool IsActive,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    IReadOnlyList<ListingImageResponse> Images,
    // ─── Product-parity fields ──────────────────────────────────────────
    string? OwnerName = null,
    string Type = "item",
    string Status = "available",
    string TransactionType = "barter",
    decimal? Price = null,
    string? DesiredSwapCategory = null,
    string? CustomCategory = null,
    double? Latitude = null,
    double? Longitude = null,
    IReadOnlyList<string>? Tags = null,
    int ViewCount = 0,
    bool IsOwnerPremium = false,
    string? ServiceCategory = null,
    string? CustomServiceCategory = null,
    int? EstimatedDuration = null,
    decimal? PriceRange = null,
    string? AvailabilitySchedule = null,
    IReadOnlyList<string>? Skills = null,
    IReadOnlyList<Guid>? InterestedUserIds = null,
    IReadOnlyList<Guid>? ViewedUserIds = null,
    IReadOnlyList<Guid>? ReportedByUserIds = null);
